### ISSUE TITLE
Trailing path parameter matches query parameters

### ISSUE THREAD

**Issue by kettanaito** [mswjs/node-match-path#15]
## Steps to reproduce

```js
match('/user/:userId', '/user/abc-123?hello=true')
```

## Current behavior

```js
{ params: { userId: 'abc-123?hello=true' } }
```

## Expected behavior

```js
{ params: { userId: 'abc-123' } }
```

_Query parameter must be disregarded during path parameter match._

**Comment by kettanaito** [comment]
Strangely, Express routing works exactly like the current unexpected behavior:

<img width="605" alt="Screen Shot 2020-05-06 at 09 46 02" src="https://user-images.githubusercontent.com/14984911/81149439-7fbd8700-8f7e-11ea-9edc-94aacdaa848d.png">

**Comment by aprilmintacpineda** [comment]
I'm actually getting this weird behavior, I think it's because we're not supposed to include the query parameters in the argument

![image](https://user-images.githubusercontent.com/21032419/121029664-5e5f4800-c7db-11eb-8d92-ae588793c55c.png)

**Comment by kettanaito** [comment]
@aprilmintacpineda, thanks for reporting this. Would you be interested in opening a pull request? I'll support you throughout your contribution and we can fix this together.
