### ISSUE TITLE
Does not work with urls that have a request content type extension and parameters

### ISSUE THREAD

**Issue by andrewswerlick-hmn** [mswjs/node-match-path#17]
I haven't tested this extensively, but I'm using this library via MSW and I think I've found a fairly common use case that is not supported. Specifically, this library will not handle a url like 
/api/books/:bookId.json. 

In manually inspecting this file https://github.com/mswjs/node-match-path/blob/master/src/pathToRegExp.ts, I believe the problem is that line 19 does not include a "." in the list of characters to terminate the parameter match. 

I'll try to submit a pull request and appropriate tests in the next day or so, but figured I'd go ahead and report the issue.

**Comment by andrewswerlick-hmn** [comment]
Note this can be easily worked around by using the undocumented fact that a regex with capture groups will result in those captures being a part of the msw `req.params` object

**Comment by kettanaito** [comment]
Hey, @andrewswerlick-hmn. That's a great catch, the matching expression indeed doesn't account for file extensions. Huge thanks for submitting the pull request! I'll look at it tomorrow and we'll solve this issue together.
